#! /bin/bash

function isOption() {
    firstChar=$(echo $1 | cut -c 1)
    test "${firstchar}" = "-"
    return $?
}

function countValues() {
    count=0
    for parameter in $@ ; do
        if isOption ${parameter} ; then
            break
        else
            ((count++))
        fi
    done
}

function add() {
    num1=$1
    num2=$2
    sum=$((${num1} + ${num2}))
    echo $sum
}

function multiply() {
    product=1
    for parameter in $@ ; do
        if isOption ${parameter} ; then
            break
        else
            product=$(( ${product} * ${parameter} ))
        fi
    done
    echo ${product}
}

function raiseError() {
    echo -e "$0: option '$1': $2 arguments required ${count}" \
        "were provided"
    }

until [ -z "$1" ] ; do
    currentParameter="$1"
    case ${currentParameter} in

        -a) shift
            numberOfValuesAccepted=2
            countValues $@
            if [ ${count} -eq ${numberOfValuesAccepted} ]
            then
                add $1 $2
            else
                raiseError ${currentParameter} ${numberOfValuesAccepted}
            fi
            ;;

        -m) shift
            minArgs=2
            maxArgs=4
            countValues $@
            if [ ${count} -lt ${minArgs} ]
            then
                echo "$0: option 'm': at least ${minArgs} values are required" \
                    "only ${count} were provided"
            elif [ ${count} -gt ${maxArgs} ]
            then
                echo "$0: option 'm': at most ${maxArgs} values are accepted" \
                    "${count} were provided"
            else
                multiply $@
            fi
            ;;

        *) shift ;;

    esac
done

