#! /bin/bash

function isOption() {
    firstChar=$(echo $1 | cut -c 1)
    test "${firstchar}" = "-"
    return $?
}

function countValues() {
    count=0
    for parameter in $@ ; do
        if isOption ${parameter} ; then
            break
        else
            ((count++))
        fi
    done
}

function add() {
    num1=$1
    num2=$2
    sum=$((${num1} + ${num2}))
    echo $sum
}

function raiseError() {
    echo -e "$0: option '$1': $2 arguments required ${count}" \
        "were provided"
    }

until [ -z "$1" ] ; do
    currentParameter="$1"
    case ${currentParameter} in

        -a) shift
            numberOfValuesAccepted=2
            countValues $@
            if [ ${count} -eq ${numberOfValuesAccepted} ]
            then
                add $1 $2
            else
                raiseError ${currentParameter} ${numberOfValuesAccepted}
            fi
            ;;

        *) shift ;;

    esac
done

