#! /bin/bash

function firstChar() {
    extractedFirstCharacter=$(echo $1 | cut -c 1)
}

function add() {
    sum=0
    i=1
    until [[ "$(firstChar ${!i})" = "-" || $i -gt $# ]] ; do
        sum=$(( ${sum}+${!i} ))
        (( i++ ))
    done
    shift
    echo $sum
}

function multiply() {
    product=1
    for parameter in $@
    do
        firstChar ${parameter}
        if [ "${extractedFirstCharacter}" != "-" ] ; then
            product=$(( ${product}*${parameter} ))
        else
            shift
            break
        fi
    done
    echo $product
}


while [ -n "$1" ]
do
    case ${1} in
        -a) shift
            sum=$(add $@)
            echo $sum
            ;;
        -m) shift
            product=$(multiply $@)
            echo $product
            ;;
        *) shift
    esac
    shift
done

